apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoin-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/bitcoin

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      containers:
      - name: bitcoin
      # replace with image from docker hub
        image: femioyebisi/bitcoin-node:latest 
        volumeMounts:
        - mountPath: /data
          name: bitcoin-data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
      volumes:
      - name: bitcoin-data
        persistentVolumeClaim:
          claimName: bitcoin-pvc
